pagopa/selfcare-dashboard-backend

connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionMapper.java

* Modified API to retrieve getInstitutions, it now also returns TOBEVALIDATED institutions
* Modified API to onboard an institution to a product, the API now also retrieves the geographic taxonomy of the onboarding institution and passes it to the BE.
* Workaround on userRole for TOBEVALIDATED institutions status
* TODO removed

Release uat

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/groups/UserGroupStatus.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserGroupConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/UserGroupRestClient.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserGroupConnectorImplTest.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/UserGroupRestClientTest.java

**List of Changes**
1. add DELETED status for userGroup
2. add status filter in UserGroupRestClient for Api getUserGroups
3. call getUserGroups with status ACTIVE, SUSPENDED
**Motivation and Context**
Logical rather than physical deletion of UserGroups
**How Has This Been Tested?**
1. Try to delete userGroup by its ID
2. Check its status from getById
3. Try to call getUserGroups (api have to returns only group with status ACTIVE or SUSPENDED)

[SELC-2434] - Add DELETED status for UserGroup, add status filter in UserGroupRestClient

---

core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java

1. add MERGE_FUNCTION during retrieve institution's products
Entity (PA) with multiple subscriptions in progress for the same product cannot access the dashboard
1. Try to login in dashboard
2. Check its happened without error

fix: Add MERGE_FUNCTION during retrieve institution's products

---

app/src/main/resources/swagger/api-docs.json
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/GeographicTaxonomyResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/InstitutionResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/InstitutionUserDetailsResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/InstitutionUserResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/PnPGInstitutionResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/onboarding/OnboardingRequestResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/BackOfficeConfigurationsResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductInfoResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductRoleInfoResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductRoleMappingsResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductUserResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductsResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/SubProductResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user/CertifiedFieldResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user/UserIdResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user/UserProductRoles.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user/UserResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user_groups/PlainUserResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user_groups/UserGroupIdResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user_groups/UserGroupPlainResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user_groups/UserGroupResource.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/model/ProductsResourceTest.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/model/product/SubProductResourceTest.java

Removed validation constraints on resources
It's not necessary to validate output objects; checks are available only for incoming dtos.
Precondition: developments for ms-product and ms-user-group were already merged into release-dev branch.
I have run pipeline for this feature branch in order to have in dev environment these developments. In addition to this, I have changed document for collection **products**, making empty the field **title** for prod-io product, and document for collection **userGroups** making empty the field **name**. Then, I haved logged into selfcare application and checked that api calls for products and user-groups were in success.
For this test, I used the following credentials:
- test/test
- Comune di Brunello
- Comune di Gaeta

Selc 2550 refactor sulle resource per be dashboard

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/InstitutionInfo.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/onboarding/OnboardingData.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/MsCoreRestClientTest.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/PartyProcessRestClientTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceTest.java

Added new claims to the IdentityToken generated by the tokenExchange controller
Since SC will allow also AOO/UO to onboard products and these products need the additionalFields related to this entities, these has to passed through the organization information claims.
The new fields are subUnitType, subUnitCode, aooParent and parentDescription
deployed from feature Branch and invoked relative API to assert the presence of the claims in the token

Refactor on tokenExchange api organization claim  #feature/SELC-2514

---

app/src/main/resources/swagger/api-docs.json
app/src/test/java/it/pagopa/selfcare/dashboard/web/config/SwaggerConfigTest.java
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/MsCoreConnector.java
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/exception/InternalGatewayErrorException.java
connector/rest/docs/openapi/api-selfcare-core-docs.json
connector/rest/pom.xml
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/MsCoreUserApiRestClient.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/config/MsCoreRestClientConfig.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/decoder/FeignErrorDecoder.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/InstitutionMapper.java
connector/rest/src/main/resources/config/ms-core-rest-client.properties
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImplTest.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/decoder/FeignErrorDecoderTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionService.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/PnPGInstitutionService.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/PnPGInstitutionServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImplTest.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/PnPGInstitutionServiceImplTest.java
pom.xml
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionController.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/PnPGInstitutionController.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/handler/DashboardExceptionsHandler.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionResourceMapper.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionControllerTest.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/PnPGInstitutionControllerTest.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/handler/DashboardExceptionsHandlerTest.java

- Introduce InstitutionResourceMapper for mapping web model
- Replace onboardingInfo with getUserProducts on core connector
- Delete some methods about pnpg classes don't use anymore
Needed to get only instutitioName and institutionId on getInstitutions API
Try to call GET /institutions with a valid token, response must have only institutionName and InstitutionId and optionally institutionRootName

refactor: get institutions by userId and replace onboardingInfo

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/InstitutionInfo.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceTest.java

Added node rootParent to TokenExhange in order to include parent description and parent identifier
In future, it will be requested to include also parent identifier so all information about root institution has been wrapped into a specific object.

Added root parent to token exchange

---

connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PagoPABackOfficeConnectorImpl.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/BrokerServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/BrokerServiceImplTest.java

Changed the default pagination start value from 1 to 0
This change was due to request of backoffice pagopa team that has exposed api to retrieve brokers considering 0 as default value
I have run dashboard-backend microservice locally and tested the specific api(/channels/brokers) getting 200 as response

Fixed start pagination for brokers

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/MsCoreConnector.java
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/DelegationRequest.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/MsCoreRestClient.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImplTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/DelegationService.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/DelegationMapper.java

**List of Changes**
- Created new object to send a delegation request to ms-core.
- Added method in DelegationMapper to manage this new entity
**Motivation and Context**
This change was due to a software regression introduced after adding new api to retrieve list of delegations.
**How Has This Been Tested?**
I have run dashboard-backend microservice locally and through Swagger, I have tested the specific api getting 200 as http code response

Fix mapper for create delegation

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/support/SupportRequest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/SupportServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/SupportServiceImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/support/SupportRequestDto.java

Added productId as query string in zendesk redirect url
This change was necessary to allow assistance layer to manage productId into zendesk form
I have run dashboard backend application locally and tested the specific api **/support**

Added productId as query string in zendesk url

---

core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImplTest.java

remove non-matching products from user instead of throw exception
Api throws an exception even if only one user's product non-match with productList
call this api with user that have active onboarding for deleted product.

fix: remove non-matching products from user's products

---

app/src/main/resources/swagger/api-docs.json
core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionService.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionController.java

Removed deprecated on getInstitutionUsers
This change was necessary to allow exposition of this API in infra for support service

Removed deprecated on getInstitutionUsers

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java

Removed null and empty objects from REST response in exchange/fatturazione and {productId}/back-office
Exchanged token must not containt null or empty values
Local environment

[SELC-3464] feat: Removed null and empty objects from exchanged token

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/SupportController.java

Added new tag external-v2 for operation that will be include into open-api for APIM
In order to avoid manual construction of open-api for APIM, all operations that will be included into this document are tagged with external-v2 or support. In this way, a step of github action will scan them and automatically include into open-api.

[SELC-3460] feat: added tag external-v2 for automatic generation of open-api

---

.github/workflows/release_open_api.yml

Updated github action with new tool to check breaking changes
This change was necessary to fix bug linked to the previous action. In particular, action failed in case of endpoints with same path and different verb.

[SELC-3516] feat: Update github action with new tool to check breaking changes

---

connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/token/TokenInfo.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImplTest.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImplTest.java

Obtained InstitutionUpdate object from Token entity, and used some of its data to map the institution to return
The api that allows you to show a pending onboarding data, used to get the institution data from the Institution collection. Instead now some of the institution data is obtained from the Token collection.
Local env

[SELC-3964] - Mapped fields of institution from token's Institution data

---

app/src/main/resources/swagger/api-docs.json
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/onboarding/OnboardingRequestInfo.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImpl.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/OnboardingRequestMapper.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/onboarding/OnboardingRequestResource.java
web/src/main/resources/swagger/swagger_en.properties

- add productId in OnboardingRequestResource
- align api-docs
Considering the new revision onboarding process for GSP with product pagoPA, the propagation of the field "productId" is mandatory, in this way the FE is able to determine whether the new card should be visualized or not.

[SELC-3874] feat: add productId in OnboardingRequestResource

---

app/src/main/resources/swagger/api-docs.json
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/exception/SupportException.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/SupportServiceImpl.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/config/CoreConfig.java
core/src/main/resources/template-zendesk/template-zendesk-form.ftl
core/src/test/java/it/pagopa/selfcare/dashboard/core/SupportServiceImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/SupportController.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/SupportControllerTest.java

- Returning an HTML page containing a Form POST with a submit directly to the Zendesk page instead of the URL redirect
Zendesk didn't want the authentication token to appear in the URL when redirected to their page. For this reason it was thought to carry out the redirect via Form. This change was initially thought to be implemented on the FE side. The problem is that the redirect to the Zendesk page through a Form caused CORS problems. To overcome the problem it was decided to implement the solution on the backend side. A Spring library already implemented on the BE side (FreeMarker) was used which allowed us to return the html page containing the form for the redirection to the Zendesk page.
The backend dashboard microservice was started locally and the redirect API was invoked, …

[SELC - 4017] feat: changed process to redirect to Zendesk Page when user is logged in

---

app/src/main/resources/swagger/api-docs.json
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/UserMapper.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/config/MethodSecurityConfig.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/RelationshipController.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluator.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluatorTest.java

- added check permission in operation with relationshipId
Currently, on the APIs that performed updates on users using the relationship ID, there were no authorization checks. Therefore, it has become necessary to add a check upstream on the user's permissions to operate on such products.

[SELC-4326] Feat: added check permission in operation with relationshipId

---

app/src/main/resources/config/application.yml
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
connector/rest/docs/openapi/selfcare-user-docs.json
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/UserPermissionRestClient.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/config/UserPermissionRestClientConfig.java
connector/rest/src/main/resources/config/user-rest-client.properties
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/config/MethodSecurityConfig.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/PartyAuthoritiesRetriever.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluatorV2.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluatorV2Test.java

- Added SelfCarePermissionEvaluatorV2 to check Permission using selfcare user API
- Added hasPermission method implementation in UserConnectorImpl
- Added condition in MethodSecurityConfig to load, as permissionEvaluator on MethodSecurityExpressionHandler, SelfCarePermissionEvaluator or SelfCarePermissionEvaluatorV2
- Added properties and condition to enable or disable PartyAuthoritiesRetrieved.
In order to move all authorization-related logic for API access to selfcare user, dashboard bff will no longer handle this logic but will instead call an API on selfcare user that will return the corresponding boolean for allowed or deny.

[SELC-4364] Feat: Added SelfCarePermissionEvaluatorV2 to check Permission using selfcare user API

---

app/src/main/resources/swagger/api-docs.json
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/UserMapper.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2Service.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserController.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/UserMapperV2.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserV2ControllerTest.java

Added endpoint to update user invoking user-ms
In order to invoke the new microservice user, a new enpoint has been added to interact with rest client for user-ms
I have run the microservice locally and tested the specific API **PUT** **/users/{id}**

[SELC-4456] feat: added endpoint to update user invoking user-ms

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionResourceMapper.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2ControllerTest.java

- refactor userRole value according to ADMIN and LIMITED
Frontend expects the values for the roles to be ADMIN and Limited, not manager, subdelegate, delegate, and operator, therefore a conversion is necessary before returning the response to the Frontend.
Local Env

[SELC-4588] Fix: refactor userRole value according to ADMIN and LIMITED

---

app/src/main/resources/swagger/api-docs.json
connector/rest/docs/openapi/selfcare-user-docs.json

Removed required params (name and familyName) from selfcare-user-docs.json for createUser API
Name and familyName are not required in order to create the user when the user taxCode already exists in PDV
local env

[SELC-4551] fix: updated selfcare-user-docs.json removing required params in User Schema

---

app/src/main/resources/config/application.yml
connector/rest/docs/openapi/selfcare-user-docs.json
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/UserMapper.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserV2ControllerTest.java

- fixed get users by institutionId to retrieve all product
- Get Users by institutionId have to returns all product for each users
local env

[SELC-4683] Fix: fixed get users by institutionId to retrieve all product

---

core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java

Added set productRole when creating an user

[SELC-4644] fix: setting productRole when creating an user

---

core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionService.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionResourceMapper.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java

- fixed retrieve token for back-office
GetToken for backoffice returned an HttpStatus 500

Fix: fixed retrieve token for back-office

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java

- Fixed ProductGrantedAuthority map when user has more productRole on productId
User could have multiple productRole on same productId, so we have to construct one ProductGrantedAuthority with list of productRole

Fix:  ProductGrantedAuthority map when user has more productRole on productId

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java

- Fixed ProductGrantedAuthority map when user has more productRole on productId
User could have multiple productRole on same productId, so we have to construct one ProductGrantedAuthority with list of productRole

Fix: ProductGrantedAuthority map when user has more productRole on productId

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
connector/rest/docs/openapi/selfcare-user-docs.json
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2Service.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserV2ControllerTest.java

- Added productRole param in suspend, activate and delete user product
When product has more than one productRole we have to filter on productRole to update userProduct status

[SELC-4835] Fix: Added productRole param in suspend, activate and delete user product

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java

- Added @PreAuthorize in searchUser by taxCode API
We have to check if logged User has permission to retrieve user details from taxCode

[SELC-4807] Feat: Added @PreAuthorize in searchUser by taxCode API

---

app/src/main/resources/config/application.yml
connector/rest/pom.xml
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PagoPABackOfficeConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserGroupConnectorImpl.java

* Added the resilience4j-spring-boot2 dependency to the pom.xml to enable resilience patterns like retry, circuit breaker, and rate limiter.
* Configured the retry properties in the application.yml to define the number of retry attempts and the wait duration between attempts.
* Added Retry annotation on get methods
This PR introduces a retry mechanism for REST GET calls in our REST clients by utilizing the resilience4j-spring-boot2 library. This enhancement aims to improve the resilience of our application by handling transient failures in external REST services more gracefully.

[SELC-4891] feat: Add Retry Mechanism to REST GET Calls using resilience4j-spring-boot2

---

connector/rest/docs/openapi/selfcare-user-docs.json
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/ProductController.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluatorV2.java

- Added @PerAuthorize for getProductBrokers API
- Refactor hasPermission method to verify the permissions even when the only parameter for the verification is the productId
We need to verify the permissions of getProductBrokers APIfor only with productId

[SELC-4802] Feat: Added @PerAuthorize for getProductBrokers API

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserGroupV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserGroupV2ServiceImplTest.java

- Refactor retrievedIds method to invoke user api to retrieve UserInstitutions instead of UserData containing data from PDV
For userGroup we need only id of user, so we can use user-be API to  retrieve UserInstitutions instead of UserData containing data from PDV

[SELC-4846] Feat: Refactor retrievedIds method

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserGroupV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserGroupV2ServiceImplTest.java

- refactor retrieveFilteredUserInstitution to remove loggedUserId as filter parameter
We don't need to filter for userId on userInstitution collection

[SELC-4846] Fix: refactor retrieveFilteredUserInstitution to remove loggedUserId as filter parameter

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java

- Added typ and sub in Jwt claims in ExchangeTokenServiceV2
To use keycloak for tokenExchange we need to add these 2 claims in token payload.

[SELC-4950] Feat: Added typ and sub in Jwt claims in ExchangeTokenServiceV2

---

app/src/main/resources/swagger/api-docs.json
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/ProductV2Controller.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/TokenV2Controller.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/ProductV2ControllerTest.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/TokenV2ControllerTest.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java

- set lang when lang parameter is already contained in BOUrl
- align openapi

[SELC-5037] fix: substitute lang in BOUrl

---

infra/container_apps/apim.tf

[APIM-v2 MIGRATION] change reference to apim-v2

---

connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/MsCoreConnector.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImplTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImplTest.java
core/src/test/resources/expectations/DelegationRequestPagoPa.json

- add product pagoPa condition in createDelegation
- add unit tests
This change was required to move product pagoPa logic from BE to BFF.
With this modification createDelegation API on ms-core is semplied and reusable.
It was tested locally by running both ms-core and bff-dashboard locally and calling createDelegation API. on bff-dashboard.
It was tested with both product prod-pagopa and prod-io.

[SELC-5224] feat: add product pagoPa condition in createDelegation

---

app/src/main/resources/swagger/api-docs.json
connector-api/pom.xml
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/DelegationWithInfo.java
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/Institution.java
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/InstitutionInfo.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/InstitutionUpdate.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/InstitutionMapper.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/onboarding/OnboardingData.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/onboarding/OnboardingPnPGData.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/BrokerServiceImpl.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImpl.java
web/pom.xml
web/src/main/java/it/pagopa/selfcare/dashboard/web/config/SwaggerConfig.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/ProductController.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/InstitutionResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/onboarding/OnboardingRequestResource.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/ProductControllerTest.java

* Replace it.pagopa.selfcare.commons.base.utils.InstitutionType with it.pagopa.selfcare.onboarding.common.InstitutionType
* Remove some enum InstitutionType with string type
* Upgrade onboarding-sdk with 0.2.1 version
This PR replace deprecated commons InstitutionType with onboarding-sdk InstitutionType. In addition, in order to avoid alert on breaking changes OpenAPI we have replaced enum type with less strict string type on InstitutionType responses

[SELC-5617] feat: Replace commons InstitutionType with onboarding-sdk InstitutionType

---

app/src/main/resources/swagger/api-docs.json
connector-api/pom.xml
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/product/mapper/ProductMapper.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java
web/pom.xml
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/ProductsMapper.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductRoleMappingsResource.java
web/src/main/resources/swagger/swagger_en.properties
web/src/test/resources/json/ProductRoleInfo.json
web/src/test/resources/json/ProductRoleMappingsResource.json

* Added phasesAdditionAllowed to response on GET /roles
* Replace legacy check of validRole with new one retrieving validRole using phasesAdditionAllowed "dashboard"
This PR aims to enable addition of roles during added users process using the config property phasesAdditionAllowed. It indicate the phases (onboarding, dashboard, dashboard-async) where adding a Selfcare role is permitted. In bff-dashboard only the roles with "dashboard" phase are permitted. This new logic replace a legacy check based on hardcoded list of [SUB_DELEGATE,OPERATOR]

[SELC-5666] feat: added phasesAdditionAllowed to response on GET /roles

---

app/src/main/resources/swagger/api-docs.json
connector-api/pom.xml
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/ProductsConnector.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/ProductConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/ProductConnectorImplTest.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/ProductService.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/ProductServiceImpl.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/ProductServiceImplTest.java
web/pom.xml
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/ProductController.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/ProductControllerTest.java

* add institutionType query param to GET /roles
* retrieve roles using getRoleMappings(institutionType)
This PR aims to retrieve roleMappings also using institutionType in "Utenti" section. It is needed when a product have different roles based on institutionType, for ex. for prod-pagopa

[SELC-5631] feat: add institutionType query param to GET /roles

---

app/src/main/resources/swagger/api-docs.json
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/OnboardedProduct.java
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/product/mapper/ProductMapper.java
connector/rest/src/test/resources/stubs/InstitutionResponse.json
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/OnboardedProductResource.java

- persist isAggregator field in API getInstitutionById
- align InstitutionResponse json used in unit tests
It was tested by running dashboard bff locally and invoking the mentioned API

[SELC-5698] feat: persist isAggregator field in API getInstitutionById

---

core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java

- Removed old code annotated with TODO on UserV2ServiceImpl
To avoid introducing regressions following a change to the method, the old code was not removed in order to ensure uninterrupted service due to the releases. Since the release of all impacted components has now been completed, the removal of the obsolete code can proceed.

[SELC-5757] Feat: Removed old code on UserV2ServiceImpl

---

app/src/main/resources/swagger/api-docs.json
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/user/ProductInfo.java
connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/user/UserInfo.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/UserMapper.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2Service.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java
pom.xml
web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/UserMapper.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductRoleInfoResource.java
web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductUserResource.java
web/src/main/resources/swagger/swagger_en.properties
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserV2ControllerTest.java

- add fiscalCode in getUsers API response
- add createdAt in getUsers API response
- add roles optional filter in getUsers API
- align openapi
- upgrade commons version to 2.5.4
This update enables the frontend to retrieve information about the Legale Rappresentante during the administration adding flow. Specifically, it allows the frontend to pre-fill the related fields (name, surname, fiscal code, and email) with the corresponding data for a better user experience.
It was tested locally

[SELC-6055] feat: add fiscalCode and createdAt fields in getUsers API and add roles filter

---

core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java

- Added a check that verifies if a user with a certain role can be assigned to a specific product directly from the dashboard by checking the phasesAdditionAllowed field in products.json
- Added a check that verifies if the specified productRoles are valid for the given role and institution based on the data in products.json
- Added the two additional checks to the dashboard APIs createInstitutionProductUser and addUserProductRole
The two additional checks provide further protection against improper use of the APIs
- Local tests
- Unit tests

[SELC-6304] feat: added checks on product phases and roles

---

web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2Controller.java
web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2ControllerTest.java

- Handling null roles and status params in getUserCount
getUserCount does not handle null roles and status parameters
- Local tests
- Unit tests

[SELC-6461] fix: roles and status params can be null in getUserCount

---

core/src/main/java/it/pagopa/selfcare/dashboard/core/SupportServiceImpl.java
core/src/main/java/it/pagopa/selfcare/dashboard/core/utils/EmailUtils.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/SupportServiceImplTest.java
core/src/test/java/it/pagopa/selfcare/dashboard/core/utils/EmailUtilsTest.java

- Added new function to get the name from the email field
Help support team better organize tickets via email instead of using first name + last name
- Local tests
- Unit tests

[SELC-6476] feat: changed how the name field in jwt token of support service is valued

---

connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java

- Added a catch ResourceNotFoundException in UserConnectorImpl -> getUserInstitutions(String userId)
The FE expects an empty list in case there are no userInstitutions associated to a userId
- Local tests
- Unit tests

[SELC-6512] fix: handling ResourceNotFoundException returned by user-ms with an empty list in GET /v2/institutions

---

pom.xml
src/test/java/it/pagopa/selfcare/dashboard/integration_test/steps/UserApiSteps.java
src/test/resources/application-test.properties

- Removed dependency spring-boot-starter-data-mongodb
- Using spring-data-commons
The dashboard doesn't need to connect to any Mongo database. The presence of this dependency triggers a health check that verifies whether a connection to a Mongo database has been established, blocking the deploy of the application.
- deploy tests

Removed spring-boot-starter-data-mongodb

---

docs/openapi/selfcare-user-docs.json
integration-test-config/mock/user-registry-api.json
src/main/java/it/pagopa/selfcare/dashboard/controller/InstitutionV2Controller.java
src/main/java/it/pagopa/selfcare/dashboard/model/CreateUserDto.java
src/main/java/it/pagopa/selfcare/dashboard/model/user/UserProductRoles.java
src/main/java/it/pagopa/selfcare/dashboard/model/user/UserToCreate.java
src/main/java/it/pagopa/selfcare/dashboard/service/UserV2Service.java
src/main/java/it/pagopa/selfcare/dashboard/service/UserV2ServiceImpl.java
src/main/resources/swagger/api-docs.json
src/main/resources/swagger/swagger_en.properties
src/test/java/it/pagopa/selfcare/dashboard/controller/InstitutionV2ControllerTest.java
src/test/java/it/pagopa/selfcare/dashboard/integration_test/steps/DashboardStepsUtil.java
src/test/java/it/pagopa/selfcare/dashboard/service/UserV2ServiceImplTest.java
src/test/resources/features/Institution.feature

- add cucumber test
- add field toAddOnAggregates to UserProductRoles in addUserProductRoles  api
- add field toAddOnAggregates to CreateUserDto in createInstitutionProductUser api
- update unit test 
Guarantee automatic management of group assignment when adding new Operator users
Tested locally

[SELC-7327] feat: add field toAddOnAggregates to addUserProductRoles and createInstitutionProductUser api
