pagopa/selfcare-dashboard-backend

- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImpl.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/PartyAuthoritiesRetriever.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluator.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceTest.java
Co-authored-by: Rodolfo Viti <rodolfo.viti@nttdata.com>
> fix filter GrantedAuthorities from SecurityContextHolder (#34)

- app/src/main/resources/swagger/api-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/onboarding/OnboardingUsersRequest.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/onboarding/User.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/PartyProcessRestClientTest.java
- connector/rest/src/test/resources/stubs/party-process/mappings/onboarding.json
Co-authored-by: Rodolfo Viti <rodolfo.viti@nttdata.com>
> fix onboarding users model (#105)

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/product/Product.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/ProductsRestClientTest.java
- connector/rest/src/test/resources/stubs/products/mappings/getProductsTree.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/config/SwaggerConfig.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/ProductsMapper.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductsResource.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/ProductsResourceTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/mapper/ProductMapperTest.java
* open api wih new productResource bgcolor field
* add logoBgColor to product Entity
* add swagger validator annotation
Co-authored-by: USERSAD\bgalgamu <bgalgamu@emeal.nttdata.com>
> release-uat

- pom.xml
Co-authored-by: USERSAD\bgalgamu <bgalgamu@emeal.nttdata.com>
> release dev

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserGroupConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserGroupConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/UserGroupRestClient.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserGroupConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/UserGroupRestClientTest.java
- connector/rest/src/test/resources/stubs/user-group/mappings/getUserGroups_fullyValued.json
- connector/rest/src/test/resources/stubs/user-group/mappings/getUserGroups_fullyValuedPageable.json
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserGroupService.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserGroupServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/UserGroupServiceImplTest.java
- pom.xml
- web/src/main/java/it/pagopa/selfcare/dashboard/web/config/SwaggerConfig.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserGroupController.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserGroupControllerTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceTest.java
* add page response model to getUSerGroups
* restore unwanted changes
Co-authored-by: Rodolfo Viti <rodolfo.viti@nttdata.com>
> Feature/selc 1420 (#123)

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserController.java
Co-authored-by: Rodolfo Viti <rodolfo.viti@nttdata.com>
> add 404 as possible response to searchUsingPOST API operation (#126)

- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceTest.java
Added Institution's name to the oranization claim in the identity token generated durign the token exchange.
> add institution name to identity token

- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceTest.java
Added Institution's name to the oranization claim in the identity token generated durign the token exchange.
> add institution name to identity token (#136)

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/InstitutionType.java
- pom.xml
* add PSP to InstitutionType enum
* update commons version
> add PSP to InstitutionType enum (#138)

- app/src/main/resources/swagger/api-docs.json
- pom.xml
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/InstitutionResource.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionMapper.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/InstitutionResourceTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionMapperTest.java
* Modified resource model for APIs getInstitution and getInstitutions. They now also retrieve the recipient code of the institution.
* Modified the recipientCode field, it is now "not required"
* Changed commons dependency from version 2.2.1 to version 2.3.0
> Release uat

- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java
**List of Changes**
1. add MERGE_FUNCTION during retrieve institution's products
**Motivation and Context**
"Ente (PA) con più adesioni in corso per lo stesso prodotto non riesce ad entrare in dashboard "
**How Has This Been Tested?**
1. Try to login in dashboard
2. Check its happened without error
> [SELC-2438] Add MERGE_FUNCTION during retrieve institution's products

- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java
for [SELC-2434] refer to https://github.com/pagopa/selfcare-dashboard-backend/pull/207
for [SELC-2438] refer to https://github.com/pagopa/selfcare-dashboard-backend/pull/208
[SELC-2434]: https://pagopa.atlassian.net/browse/SELC-2434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-2438]: https://pagopa.atlassian.net/browse/SELC-2438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-2438] Add MERGE_FUNCTION during retrieve institution's product - [SECL-2434] Add DELETED status for userGroup

- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
add imprese.{env}.notifichedigitali.it to cors-allow-origin in pnpg/helm
pnpg moved url from pnpg.selfcare.it to imprese.notifichedigitali.it
Navigate to imprese.notifichedigitali.it
> ops: add imprese.env.notifichedigitali.it to cors-allow-origin

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/product/Product.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/ProductsMapper.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/ProductsResource.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/product/SubProductResource.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/main/resources/swagger/swagger_it.properties
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/mapper/ProductMapperTest.java
added delegable attribute to ProductResource @GET /institution/{id}/products
FE needed to know which products is delegable
Try to call GET /institution/{institutionId}/products with a institution that has an onboarding on prod-io or prod-pagopa, product resource must have delegable attribute as true
> feat: added delegable attribute product @/institution/{id}/products

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/MsCoreConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/Delegation.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/delegation/DelegationRequestDto.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/DelegationControllerTest.java
Added new field into delegation entity in order to save partner's name
This change was necessary to avoid aggregation into queries and reduce performances of services
I have run microservice locally aiming to dev env and tested specific api to create a delegation.
> Added new field into delegation object: instituionToName

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/Delegation.java
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImplTest.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/delegation/DelegationResource.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/DelegationMapper.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionControllerTest.java
> [SELC - 2781] updated delegation variable name

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/InstitutionInfo.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PartyConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/onboarding/OnboardingData.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/MsCoreRestClientTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/PartyProcessRestClientTest.java
- connector/rest/src/test/resources/stubs/party-process/mappings/getInstitution_fullyValued.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
Added root parent id as attribute of response of onboaring/info api in order to manage this field in ExchangeTokenService
It's necessary to manage this field into dashboard backend 
I have tested the api onboarding/info api locally, aiming to dev environment
> Added rootParentId into TokenExchange

- connector/rest/docs/openapi/api-selfcare-backoffice-docs.json
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/PagoPABackOfficeRestClientTest.java
- connector/rest/src/test/resources/stubs/brokers/mappings/getBrokersPSP.json
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Changed base url of backoffice pagopa for each environment.
This change was necessary to bind correct api's set of backoffice pagopa backend
I have deployed the feature branch in dev environment.
> Changed base url backoffice pagopa for each environment

- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/Institution.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/RootParentResponse.java
- connector/rest/src/test/resources/stubs/ms-core/mappings/getInstitutionByExternalId_fullyValued.json
- connector/rest/src/test/resources/stubs/ms-core/mappings/getInstitution_fullyValued.json
- connector/rest/src/test/resources/stubs/party-management/mappings/getInstitutionByExternalId_fullyValued.json
- connector/rest/src/test/resources/stubs/party-process/mappings/getInstitutionByExternalId_fullyValued.json
- connector/rest/src/test/resources/stubs/party-process/mappings/getInstitution_fullyValued.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionResourceMapper.java
Add subunitCode, subunitType, aooParentCode and rootParent in Institution model, map in InstitutionResource
Dashboard FE required these fields
called institutions/{institutionId} and check these fields
> fix: Add fields in institution Model

- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionService.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionController.java
Added deprecated and PreAuthorize to getInstitutionUsers API
This change is necessary to revert development into branch feature/SELC-2980
> Added deprecated and PreAuthorize to getInstitutionUsers API

- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/MsCoreConnector.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/MsCoreRestClient.java
- connector/rest/src/main/resources/config/ms-core-rest-client.properties
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/MsCoreConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/UserServiceImplTest.java
implement call to ms-core to notify user detail update changes
User details change has to be notified to external interceptor
> implement call to ms-core to notify user detail update changes

- web/src/main/java/it/pagopa/selfcare/dashboard/web/handler/DashboardExceptionsHandler.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/handler/DashboardExceptionsHandlerTest.java
Added handler http in case of AccessDeniedException to return forbidden.
When a user is not authorize backend return http 500 error.
> hotfix: handle access denied as forbidden

- README.md
- connector/rest/src/main/resources/config/ms-core-rest-client.properties
- connector/rest/src/main/resources/config/party-management-rest-client.properties
- connector/rest/src/main/resources/config/party-process-rest-client.properties
- connector/rest/src/main/resources/config/party-registry-proxy-rest-client.properties
- connector/rest/src/main/resources/config/products-rest-client.properties
- connector/rest/src/main/resources/config/user-group-rest-client.properties
Added description of microservie and how start locally
Set default values of some properties
README repo must have some description about context and how start if a new dev would clone it and start locally.
> docs: update README with description and instructions how start locally

- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
Check if workcontracts mail is not null before setting in claims when we create a toke exchange
> fix: set mail on token exchange

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .devops/pnpg-code-review-pipelines.yml
- .devops/pnpg-deploy-pipelines.yml
- Dockerfile
- connector/azure-storage/src/test/java/it/pagopa/selfcare/dashboard/connector/azure_storage/AzureBlobClientTest.java
- pom.xml
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/mapper/GroupMapperTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/mapper/PnPGInstitutionMapperTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/model/mapper/ProductMapperTest.java
- updated starter-parent version from 0.0.2 to 0.0.3 for jdk 17 update
- updated pipelines from 1.11 to 1.17
These updates are necessary as there is a need to upgrade to java 17
> [SELC-3371] feat: Update to jdk 17

- helm/values-dev.yaml
Formatting thing
Consistency across repos
> [SELC-3339] Format dev ingress definition

- helm/values.yaml
PDB disabled for all environments
This service has a single replica, we can't enforce PDB policies then
> [SELC-3339] Disable PDB for all environments

- app/src/main/resources/swagger/api-docs.json
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserGroupService.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/config/ExchangeTokenProperties.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/TokenController.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenService.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluator.java
- web/src/main/resources/config/token-exchange.properties
- web/src/main/resources/swagger/swagger_en.properties
- web/src/main/resources/swagger/swagger_it.properties
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/TokenControllerTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceTest.java
* added first implementation of exchange/fatturazione
* remove duplication and fix tests
> [SELC-3407] Feat: API for token/exchange/fatturazione (#292)

- app/src/main/resources/swagger/api-docs.json
- connector/rest/docs/openapi/api-selfcare-backoffice-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/PagoPABackOfficeConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/MsBackOfficeChannelApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/MsBackOfficeStationApiClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/BrokerMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/PagoPABackOfficeConnectorImplTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/client/PagoPABackOfficeRestClientTest.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/mapper/BrokerMapperImplTest.java
- connector/rest/src/test/resources/stubs/brokers/mappings/getBrokersEC.json
- connector/rest/src/test/resources/stubs/brokers/mappings/getBrokersPSP.json
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Changed base path for backoffice pagopa client
The base path for client has been changed by backoffice. So It has been necessary to regenerate endpoints for retrieving list of partners.
The branch has been deployed in DEV environment and the development has been tested through dashboard frontend.
> [SELC-3502] bug: Changed base path for backoffice pagopa client

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/OnboardingRequestMapper.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/onboarding/OnboardingRequestResource.java
- change agentOfPublicServiceNote  type from boolean to string
> [SELC-3793] fix: modify agentOfPublicServiceNote type and update swagger

- .github/workflows/opex_api.yml
Adding new github action for opex dashboard
> feat: Adding gihub action

- .github/workflows/opex_api.yml
> fix: Opex folder

- .opex/api-selfcare-dashboard/env/prod/config.yaml
> fix: Opex name

- .github/workflows/opex_api_pnpg.yml
- .opex/api-selfcare-dashboard-pnpg/env/prod/backend.ini
- .opex/api-selfcare-dashboard-pnpg/env/prod/backend.tfvars
- .opex/api-selfcare-dashboard-pnpg/env/prod/config.yaml
- .opex/api-selfcare-dashboard-pnpg/env/prod/terraform.tfvars
> [SELC-2952] Add Opex to PNPG

- .github/workflows/opex_api.yml
- .github/workflows/opex_api_pnpg.yml
> [SELC-2952] fix: opex action name

- .opex/api-selfcare-dashboard-pnpg/env/prod/backend.tfvars
- .opex/api-selfcare-dashboard-pnpg/env/prod/config.yaml
> [SELC-2952] fix: opex host

- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/client/UserApiRestClient.java
Fix rest client properties for UserApiClient
Modified placeholder for UserApiClient in order to bind correct application properties
> Fix rest client properties for UserApiClient

- .opex/api-selfcare-dashboard-pnpg/env/prod/config.yaml
- .opex/api-selfcare-dashboard/env/prod/config.yaml
> [SELC-2952] fix alert

- .opex/api-selfcare-dashboard-pnpg/env/prod/config.yaml
- .opex/api-selfcare-dashboard/env/prod/config.yaml
> [SELC-2952] fix Endpoints configuration

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/onboarding/OnboardingRequestResource.java
- remove "recipientCode" as a mandatory field from InstitutionInfo
- remove "manager" as a mandatory field from OnboardingRequestResource
- remove "id" as a mandatory field from InstitutionInfo
- align api.docs
These changes were necessary because recipientCode and manager fields are not required for PT, instead for institutionId in the new onboarding flow the institution is created after the onboarding request, for this reason the institutionId is no longer required
> [SELC-4177] feat: remove recipientCode and manager from required fields

- .dockerignore
- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_my_pnpg.yml
- Dockerfile.new
- Dockerfile.new.dockerignore
- pom.xml
Add workflows
Migrating to container apps
> [EC-151] Add microservice pipelines

- .opex/api-selfcare-dashboard/env/prod/config.yaml
Tuning availability alerts for opex dashboard
> fix: Update opex configuration

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/Institution.java
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/InstitutionResource.java
- web/src/main/resources/swagger/swagger_en.properties
- add delegation field in getInstitution
- align api-docs for dashboard
- align core openapi
This change raises from the addition of "delegation" field in Institution to mark institutions that have a delegation.
This change has been tested by running ms locally and calling the indicated API.
> [SELC-4173] feat: add delegation field in getInstitution

- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Added variables for base url of user-ms into helm directory.
Adding these variables, it will be possible to invoke from this bff new microservice that wraps logic of user resource
> [SELC-4422] feat: added variables for base url of user-ms

- .github/workflows/release_open_api.yml
- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/dashboard/web/config/SwaggerConfigTest.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
- connector/rest/docs/openapi/selfcare-user-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/UserMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2Service.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/UserMapperV2.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user/UserResource.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user/WorkContactResource.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserV2ControllerTest.java
> resolve uat conflicts

- connector/rest/src/main/resources/config/user-rest-client.properties
Added auth interceptor for user-ms rest client
With this request interceptor, dashboard bff will invoke the user microservice injecting token into header authorization.
I have deployed the bufgix branch directly in dev and tested the API for user suspension
> [SELC-4422] fix: added auth interceptor for user-ms rest client

- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionController.java
-  Added @PreAuthorize in updateInstitutionGeographicTaxonomy API 
We need to check User Permission to update institution By verifying that the user has at least one active product associated with the institution.
> [SELC-4204] Feat: Added @PreAuthorize in updateInstitutionGeographicTaxonomy API

- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- .github/workflows/release_my_pnpg.yml
- Dockerfile.new
- infra/container_apps/.terraform.lock.hcl
- infra/container_apps/README.md
- infra/container_apps/env/dev-pnpg/backend.ini
- infra/container_apps/env/dev-pnpg/backend.tfvars
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/backend.ini
- infra/container_apps/env/dev/backend.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/backend.ini
- infra/container_apps/env/prod-pnpg/backend.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/backend.ini
- infra/container_apps/env/prod/backend.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/backend.ini
- infra/container_apps/env/uat-pnpg/backend.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/backend.ini
- infra/container_apps/env/uat/backend.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/main.tf
- infra/container_apps/terraform.sh
- infra/container_apps/variables.tf
Add Terraform moudle to deploy microservice on Container App
Migration to Container Apps
> [EC-120] Add Container App infrastructure

- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
JWT_TOKEN_PUBLIC_KEY misses as env variable
> [EC-120] fix: added JWT_TOKEN_PUBLIC_KEY as secret

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/dashboard/web/config/SwaggerConfigTest.java
- infra/container_apps/.terraform.lock.hcl
- infra/container_apps/apim.tf
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/variables.tf
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/InstitutionResource.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/user/UserResource.java
Added apim group BFF dashboard for migration to Container Apps
> [SELC-4510] Added apim group BFF dashboard for ca

- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/InstitutionBase.java
- connector/rest/docs/openapi/selfcare-user-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/InstitutionMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2Service.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionResourceMapper.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserV2ControllerTest.java
- Refactor API to retrieve list of user's institution after dashboard login
This APi is used to retrieve user's institution List after login in dahsboard FE. So we need to return correct response to simplify bff logic
> [SELC-4532] Fix: Refactor API to retrieve list of user's institution after dashboard login

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2Controller.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2ControllerTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/UserV2ControllerTest.java
Changed request mapping for UserV2Controller from **/v2** to **/v2/users**
> [SELC-4534] feat: added request mapping users v2 to UserV2Controller

- app/src/main/resources/swagger/api-docs.json
- core/src/main/java/it/pagopa/selfcare/dashboard/core/SupportService.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/SupportServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/SupportServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/SupportController.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/SupportControllerTest.java
Added endpoint for zendesk integraton to fix error in pnpg
In order to solve temporarily the error for zendesk integration  in pnpg, a new endpoint has been added to skip the submit of the form and return directly the url of zendesk. This method appears as deprecated beacuse it will be removed as soon as the solution with form sumbit will be implemented correctly.
I have run the microservice locally and tested the mentioned API
> [SELC-4535] feat: added endpoint for zendesk integraton to fix error in pnpg

- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
This environment variable is used to retrieve authorities for logged user and in pre-authorize process to detect the way to check permissions, calling oldest version of apis or newest one.
> [SELC-4484] feat: Added variable to switch check authorities to v2

- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/user/CertifiedField.java
- connector/rest/docs/openapi/selfcare-user-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/UserMapper.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/UserMapperV2.java
fixed incorrect Mapping of userCertified fileds
Incorrect mapping due to incompatible deserialization objects in rest api call
locally tested
> [SELC-4644] fix: user fileds certification mapping issue

- connector/rest/docs/openapi/selfcare-user-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/exception/InvalidOnboardingStatusException.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImplTest.java
- Added check to insitution.onboarding in createUser and addUserProductRole
When we createNewUser we need to check if product is already onboarded on the institution
local env
> [SELC-4645] Fix: added check to insitution.onboarding in createUser and addUserProductRole

- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImpl.java
- Fixed userRole value in getInstitutionById
The getInstitutionById API was returning PartyRole instead of SelfcareAuthority
> [SELC-4656] Fix: userRole value in getInstitutionById

- .github/workflows/release_open_api.yml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
* Remove workload_profile_name variables because is default on terraform module
* Change PNPG dns suffix url
Migration to new Container Apps environment with Workload profile
> chore: Workload profiles migration PNPG

- .github/workflows/pr_ms.yml
- helm/pnpg/values-dev.yaml
- helm/pnpg/values-prod.yaml
- helm/pnpg/values-uat.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- infra/container_apps/README.md
- infra/container_apps/apim.tf
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/locals.tf
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
* Container App env name must be specified
* workload_profile null for dev and prod
Container App env could have a different configuration among dev or uat or prod.
> chore: Migration to Container App module with name and workload_profile empty

- core/src/main/java/it/pagopa/selfcare/dashboard/core/UserV2ServiceImpl.java
Added filter to remove products from userinstitution records when state isn't allowed, in retrieveUsers API.
The fix is mandatory and is a filter on the status of products after the query results are retrieved, because currently the API only performs a filter on the query, but because of the structure of the UserInstitution collection if a user has multiple products both those with the desired status and those with the status to be discarded are returned.
> [SELC-4683] fix: added filter to remove products from userinstitution records when state isn't allowed

- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
> chore: B4F_DASHBOARD_SECURITY_CONNECTOR switch to v2

- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
Added sorted in user's institutions list
We need to order list of user's institution by institution name
local env
> [SELC-4587] Feat: Added sorted in user's institutions list

- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
> chore: set B4F_DASHBOARD_SECURITY_CONNECTOR to v2 for uat and prod

- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
- Fixed sort institution list when institution name is null
When user's institutitions have null institution name we have to set these items at the end of the sorted list instead of throws an exception
> [SELC-4587] Fix: fixed sort institution list when institution name is null

- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/mapper/InstitutionResourceMapper.java
Fix setting institutionInfo.getRootParent()
> hotfix: mapping token exchange root

- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java
Fixed token exchange to filter only for ACTIVE products
We have to put in jwt generated from token exchange only active Products
> Fix: token exchange to filter only for ACTIVE products

- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java
Fix tests on ExchangeTokenServiceV2Test
merge back from release have broken tests
> Fix tests on ExchangeTokenServiceV2Test

- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImplTest.java
Added filter on ACTIVE product when set authorization on instutitons by id
> hotfix: set authorization based on ACTIVE products

- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/BrokerMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImplTest.java
- mapped institution taxCode in brokerInfo code
We need to have taxCode for broker code instead of institutionId
> [SELC-4864] Feat: mapped institution taxCode in brokerInfo code

- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/DelegationController.java
- Added @PreAuthorize in createDelegation API
We have to check if logged User has permission to createDelegation.
> [SELC-4798] Added @PreAuthorize in createDelegation API

- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserGroupV2Controller.java
- Added @PreAuthorize in createUserGroup API
We have to check if logged User has permission to create user group
> [SELC-4808] Added @PreAuthorize in createUserGroup API

- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserV2Controller.java
- Added @PreAuthorize in getUserById API
We have to check if logged User has permission to retrieve user details
> [SELC-4806] Feat: Added @PreAuthorize in getUserById API

- web/src/main/java/it/pagopa/selfcare/dashboard/web/config/MethodSecurityConfig.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserGroupV2Controller.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluatorV2.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/SelfCarePermissionEvaluatorV2Test.java
-  Added @PreAuthorize in activateUserGroup API
-  Added retrieve institutionId and ProductId from userGroup for permission
We have to check if logged User has permission to activate user group
> [SELC-4810] Feat: Added @PreAuthorize in activateUserGroup API, added retrieve institutionId and ProductId from userGroup for permission

- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/UserGroupV2Controller.java
- Added @PreAuthorize in DeleteUserGroup API
We have to check if logged User has permission to delete user group
> [SELC-4809] Feat: Added @PreAuthorize in DeleteUserGroup API

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/MsCoreConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/DelegationWithInfo.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/DelegationWithPagination.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/PageInfo.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/DelegationRestClientMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/DelegationService.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/DelegationServiceImplTest.java
- web/pom.xml
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionController.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2ControllerTest.java
- add v2 of API getDelegations
- add unit tests
- align openapi
It was tested by running locally dashboard ms and calling getDelegationsV2 API
> [SELC-4839] feat: add v2 of API getDelegations to manage pagination

- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/TokenV2Controller.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/TokenV2ControllerTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java
- remove lang from billingUrl in exchange/fatturazione API
> hotfix: remove lang from billingUrl in exchange/fatturazione API

- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/TokenV2Controller.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/TokenV2ControllerTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java
- remove lang from billingUrl in exchange/fatturazione API
> [SELC-5037] fix: remove lang from billingUrl in exchange/fatturazione API

- connector-api/pom.xml
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/exception/InvalidRequestException.java
- connector-api/src/test/java/exception/InvalidRequestExceptionTest.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/exception/InvalidRequestExceptionTest.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/security/ExchangeTokenServiceV2Test.java
Fix Nullpointer in ExchangedToken exchange
Junit Test
> [SELC-5271] bugfix : Nullpointer in ExchangedToken exchange

- infra/container_apps/env/uat/terraform.tfvars
> chore: Move to Container App Env workload UAT

- infra/container_apps/README.md
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
> chore: Move to Container App Env workload PROD

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/UserApiConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/institution/OnboardedProduct.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/user/OnboardedProductWithActions.java
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/user/UserInstitutionWithActionsDto.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/UserMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImplTest.java
- core/src/test/resources/expectations/UserInstitutionWithActions.json
- core/src/test/resources/expectations/UserInstitutionWithActionsOperator.json
- web/src/main/java/it/pagopa/selfcare/dashboard/web/model/OnboardedProductResource.java
- web/src/test/resources/json/Institution.json
- web/src/test/resources/json/InstitutionResource.json
Refactor api getInstitution to retrieve list of user product actions in addition to boolean authorize
We need to work with new concept of Actions instead of simple boolean
> [SELC-5249] Feat: Refactor api getInstitution to retrieve list of user product actions in addition to boolean authorize

- connector/rest/docs/openapi/selfcare-user-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/InstitutionMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/UserMapper.java
- Updated selfcare-user-docs.json to latest version
> [SELC-5335] Feat: Updated selfcare-user-docs.json to latest version

- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
fixed ONBOARDING_URL env value, setting "http" instead of "https"
> [SELC-5327] fix: path in ONBOARDING_URL env

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/api/OnboardingConnector.java
- connector/rest/docs/openapi/selfcare-onboarding-openapi.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/OnboardingConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/OnboardingConnectorImplTest.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionV2Service.java
- core/src/main/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/dashboard/core/InstitutionV2ServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2Controller.java
- web/src/test/java/it/pagopa/selfcare/dashboard/web/controller/InstitutionV2ControllerTest.java
- Changed filter to retrieve pending onboarding
We need to retrieve Pending onboardign filtering by taxCode e optional subunitCode
> [SELC-5388] Feat: Change filter to retrieve pending onboarding

- connector-api/pom.xml
- web/pom.xml
Increase sdk product version 0.2.0
> [SELC-5520] feat: increase sdk product version to handle institutionContractMapping issue

- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
- fixed method to map onboarding product Actions
If onboardingProductActions returned by user-ms are null, we have a nullpointerexception, so we need to fix this behavior
> Fix: fixed method to map onboarding product Actions

- connector/rest/docs/openapi/selfcare-onboarding-openapi.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/OnboardingConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/OnboardingConnectorImplTest.java
SubunitType misses EC type causing some issues in PROD env
> hotfix: update openapi onboarding-ms and automatic client

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/dashboard/connector/model/delegation/DelegationType.java
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/model/mapper/InstitutionMapper.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImplTest.java
- pom.xml
- replace ms-institution openapi
- align mappers
- update common version to 2.5.3 to add ADMIN_EA SelfcareAuthority
- add EA delegationType
- align tests
- align dashboard bff openapi
> [SELC-5695] fix: replace ms-institution openapi and align mappers and tests

- connector-api/pom.xml
- connector/rest/docs/openapi/selfcare-user-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/UserConnectorImplTest.java
- align user-ms openapi
- replace new generated API in UserConnectorImpl
It was tested locally
> [SELC-5847] fix: align openapi user to allow ADMIN_EA role

- connector-api/pom.xml
- connector/rest/docs/openapi/api-selfcare-core-docs.json
- connector/rest/src/main/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/dashboard/connector/rest/CoreConnectorImplTest.java
- connector/rest/src/test/resources/stubs/Product.json
- connector/rest/src/test/resources/stubs/ProductList.json
- connector/rest/src/test/resources/stubs/ProductTree.json
- core/src/test/resources/expectations/ProductTree.json
- pom.xml
- web/pom.xml
- update core swagger
- upgrade selfcare-commons version from 2.5.4 to 2.5.5
- upgrade onboarding-sdk to 0.6.2
This change is required to manage GPU institutionType in dashboard bff
> [SELC-6226] feat: manage GPU InstitutionType

- .github/workflows/release_ms.yml
- add path_openapi_docs spec in release_ms.yml
Fix openapi release during pipeline deploy
Local test
> [SELC-6207] fix: add path_openapi_docs spec in release_ms.yml

- .github/workflows/release_ms_pnpg.yml
- Added correct api-docs.json path
Missing api-docs.json path
> Fix release_ms_pnpg.yml workflow

- src/main/java/it/pagopa/selfcare/dashboard/controller/InstitutionV2Controller.java
- src/main/java/it/pagopa/selfcare/dashboard/model/mapper/OnboardingMapper.java
- src/main/java/it/pagopa/selfcare/dashboard/model/user/OnboardingInfo.java
- src/main/java/it/pagopa/selfcare/dashboard/service/InstitutionV2Service.java
- src/main/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImpl.java
- src/main/java/it/pagopa/selfcare/dashboard/service/UserGroupV2ServiceImpl.java
- src/main/resources/swagger/api-docs.json
- src/main/resources/swagger/swagger_en.properties
- src/test/java/it/pagopa/selfcare/dashboard/config/SwaggerConfigTest.java
- src/test/java/it/pagopa/selfcare/dashboard/controller/InstitutionV2ControllerTest.java
- src/test/java/it/pagopa/selfcare/dashboard/integration_test/model/Filter.java
- src/test/java/it/pagopa/selfcare/dashboard/integration_test/steps/DashboardBaseSteps.java
- src/test/java/it/pagopa/selfcare/dashboard/integration_test/steps/InstitutionApiSteps.java
- src/test/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImplTest.java
- src/test/resources/features/Institution.feature
- add new API getOnboardingsInfo
- add unit tests
- add cucumber tests
This API is required for new document section feature
It was tested locally
> [SELC-6617] feat: add new api getOnboardingsInfo

- .github/workflows/create_release_branch.yml
- update ubuntu version in create_release_branch workflow
ubuntu 20.04 is deprecated
> Update ubuntu version in create_release_branch workflow

- .github/workflows/release_ms.yml
- Updated ubuntu version in release_ms workflow
ubuntu 20.04 is deprecated
> Updated ubuntu version in release_ms workflow

- docker-compose.yml
- docs/openapi/selfcare-onboarding-openapi.json
- integration-test-config/blobStorageInit/initAzurite.sh
- integration-test-config/blobStorageInit/signed_IO_accordo_adesione.pdf
- integration-test-config/db/tokens.json
- src/main/java/it/pagopa/selfcare/dashboard/client/TokenRestClient.java
- src/main/java/it/pagopa/selfcare/dashboard/config/OnboardingRestClientConfig.java
- src/main/java/it/pagopa/selfcare/dashboard/controller/InstitutionV2Controller.java
- src/main/java/it/pagopa/selfcare/dashboard/service/InstitutionV2Service.java
- src/main/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImpl.java
- src/main/resources/config/onboarding-rest-client.properties
- src/main/resources/swagger/api-docs.json
- src/main/resources/swagger/swagger_en.properties
- src/test/java/it/pagopa/selfcare/dashboard/controller/BaseControllerTest.java
- src/test/java/it/pagopa/selfcare/dashboard/controller/InstitutionV2ControllerTest.java
- src/test/java/it/pagopa/selfcare/dashboard/integration_test/steps/InstitutionApiSteps.java
- src/test/java/it/pagopa/selfcare/dashboard/security/ExchangeTokenServiceV2Test.java
- src/test/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImplTest.java
- src/test/resources/features/Institution.feature
- add new API getContract
- add unit tests
This API is required for new document section feature
It was tested locally, with junit and cucumber tests
> [SELC-6618] feat: add new API getContract

- src/main/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImpl.java
- src/main/java/it/pagopa/selfcare/dashboard/service/UserV2ServiceImpl.java
- src/test/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImplTest.java
- src/test/resources/features/User.feature
- modify filter roles logic in API getUsers
- refactor to avoid duplication of code
- add cucumber tests
When the API was invoked with a roles filter, it wasn't correctly applied
It was tested locally
> [SELC-7133] fix: modify filter roles in API getUsers

- infra/container_apps/main.tf
Updating removing probe from container
> [SELC-7498] fix: Updated infra modules to v4

- src/main/java/it/pagopa/selfcare/dashboard/controller/InstitutionV2Controller.java
- src/main/java/it/pagopa/selfcare/dashboard/controller/UserV2Controller.java
- Using new permissions CreateProductUsers, UpdateProductUsers, DeleteProductUsers
Assign the new actions to the APIs
- Local tests
- Unit tests
- Integration tests
> [SELC-7644] Using new permissions CreateProductUsers, UpdateProductUsers, DeleteProductUsers

- src/main/java/it/pagopa/selfcare/dashboard/service/DelegationServiceImpl.java
- Removed filter PT when creating a delegation for prod-pagopa
Delegations can also be made for PA and GPS in the case of prod-pagopa
- Local tests
> [SELC-7754] Removed filter PT when creating a delegation for prod-pagopa

- integration-test-config/azure-cli/Dockerfile-azure-cli
- updated alpine image in Dockerfile-azure-cli
Allow git clone of the selfcare-infra repository for cucumber integration test
> [SELC-7788] feat: update alpine image in Dockerfile-azure-cli

- docs/openapi/api-selfcare-core-docs.json
- pom.xml
- src/main/java/it/pagopa/selfcare/dashboard/service/DelegationServiceImpl.java
- src/main/java/it/pagopa/selfcare/dashboard/service/InstitutionServiceImpl.java
- src/main/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImpl.java
- src/main/java/it/pagopa/selfcare/dashboard/service/UserV2ServiceImpl.java
- src/main/resources/swagger/api-docs.json
- src/test/java/it/pagopa/selfcare/dashboard/service/DelegationServiceImplTest.java
- src/test/java/it/pagopa/selfcare/dashboard/service/InstitutionServiceImplTest.java
- src/test/java/it/pagopa/selfcare/dashboard/service/InstitutionV2ServiceImplTest.java
- src/test/java/it/pagopa/selfcare/dashboard/service/UserV2ServiceImplTest.java
- upgrade onboarding-sdk version to add new institution types SCEC and PRV_PF
- update institution-ms openapi
This change is intended to handle the new institution types SCEC and PRV_PF
> [SELC-7759] feat: upgrade onboarding sdk version to add new institution types
